Add ecs version
bcgov/nr-ansible pull request #50
Opened 2021-12-31 19:22 UTC by andrwils

We should start sending the ecs version with all events. I've added the ecs version of 1.12.0 to the base filter configuration.

2021-12-31 20:09 UTC, mbystedt requested changes

2021-12-31 20:09 UTC, mbystedt commented on roles/apm_agent/files/conf/filters.conf
> +        Name nest
Tabbing seems a bit off.

2021-12-31 22:04 UTC, andrwils commented on roles/apm_agent/files/conf/filters.conf
> +        Name nest
Tabbing corrected

2022-01-04 17:12 UTC, mbystedt approved these changes

2022-01-04 23:44 UTC, merged